version: '2'
services:
  website:
    image: php:apache
    depends_on:
      - api
    ports:
      - "8081:80"
    volumes:
      - ./website:/var/www/html
    environment:
      - USERNAME=toto
      - PASSWORD=python
    networks:
      - website_network

  api:
    image: studentlist_api:v1
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    ports:
      - "8082:5000"
    networks:
      - website_network

networks:
  website_network:
